[package]
name = "verification-script"
description = "A cargo-generate template for Rust + Sway integration testing."
version = { workspace = true }
edition = { workspace = true }
authors = { workspace = true }
license = { workspace = true }
repository = { workspace = true }

[dev-dependencies]
ethers-core = { workspace = true }
ethers-signers = { workspace = true }
fuels = { workspace = true }
tokio = { workspace = true }

[[test]]
harness = true
name = "integration_tests"
path = "tests/harness.rs"
