/* Autogenerated file. Do not edit manually. */

import { Predicate as Predicate1722565073112 } from './0xca07380d3c0d9890519ee727bf522eaf19e2acefab240c9a22b0aa90f41c87d6';

export default {
  '0xca07380d3c0d9890519ee727bf522eaf19e2acefab240c9a22b0aa90f41c87d6': {
    predicate: Predicate1722565073112,
    generatedAt: 1722565073112,
  },
};
