/* Autogenerated file. Do not edit manually. */

import {
  abi as abi1725378657830,
  bin as bin1725378657830,
  generationDate as generationDate1725378657830,
} from './0xb2e7afecbc573e7412ca0bbb8d8f01d75c5c63f09e14c0921913ca9b7df70e63';

export const PREDICATE_VERSIONS = {
  '0xb2e7afecbc573e7412ca0bbb8d8f01d75c5c63f09e14c0921913ca9b7df70e63': {
    predicate: { abi: abi1725378657830, bin: bin1725378657830 },
    generatedAt: generationDate1725378657830,
  },
};
