/* Autogenerated file. Do not edit manually. */

/* tslint:disable */
/* eslint-disable */

/*
  Fuels version: 0.92.0
  Forc version: 0.61.2
  Fuel-Core version: 0.31.0
*/

import type {
  BN,
  BigNumberish,
  BytesLike,
  Contract,
  DecodedValue,
  FunctionFragment,
  Interface,
  InvokeFunction,
} from 'fuels';

export type VerificationPredicateAbiConfigurables = {
  SIGNER: string;
};

interface VerificationPredicateAbiInterface extends Interface {
  functions: {
    main: FunctionFragment;
  };
}

export class VerificationPredicateAbi extends Contract {
  interface: VerificationPredicateAbiInterface;
  functions: {
    main: InvokeFunction<[witness_index: BigNumberish], boolean>;
  };
}
