/* Autogenerated file. Do not edit manually. */

import {
  abi as abi1725378707686,
  bin as bin1725378707686,
  generationDate as generationDate1725378707686,
} from './0x1ba422983aae00d46ebdb6201bcaadc3125c40e4972855286ac01714511bf61a';

export const PREDICATE_VERSIONS = {
  '0x1ba422983aae00d46ebdb6201bcaadc3125c40e4972855286ac01714511bf61a': {
    predicate: { abi: abi1725378707686, bin: bin1725378707686 },
    generatedAt: generationDate1725378707686,
  },
};
