/* Autogenerated file. Do not edit manually. */

import { Predicate as Predicate1722564535077 } from './0xce634e314f83a76fcdd0ca23f6f2ceecd05e771893b356aa035a6c1d5612e11d';

export default {
  '0xce634e314f83a76fcdd0ca23f6f2ceecd05e771893b356aa035a6c1d5612e11d': {
    predicate: Predicate1722564535077,
    generatedAt: 1722564535077,
  },
};
