/* Autogenerated file. Do not edit manually. */

/* tslint:disable */
/* eslint-disable */

/*
  Fuels version: 0.92.0
  Forc version: 0.61.2
  Fuel-Core version: 0.31.0
*/

import { Interface, Contract, ContractFactory } from "fuels";
import type { Provider, Account, AbstractAddress, BytesLike, DeployContractOptions, StorageSlot, DeployContractResult } from "fuels";
import type { VerificationPredicateAbi, VerificationPredicateAbiInterface } from "../VerificationPredicateAbi";

const _abi = {
  "encoding": "1",
  "types": [
    {
      "typeId": 0,
      "type": "b256",
      "components": null,
      "typeParameters": null
    },
    {
      "typeId": 1,
      "type": "bool",
      "components": null,
      "typeParameters": null
    },
    {
      "typeId": 2,
      "type": "u64",
      "components": null,
      "typeParameters": null
    }
  ],
  "functions": [
    {
      "inputs": [
        {
          "name": "witness_index",
          "type": 2,
          "typeArguments": null
        }
      ],
      "name": "main",
      "output": {
        "name": "",
        "type": 1,
        "typeArguments": null
      },
      "attributes": null
    }
  ],
  "loggedTypes": [],
  "messagesTypes": [],
  "configurables": [
    {
      "name": "SIGNER",
      "configurableType": {
        "name": "",
        "type": 0,
        "typeArguments": null
      },
      "offset": 3176
    }
  ]
};

const _storageSlots: StorageSlot[] = [];

export const VerificationPredicateAbi__factory = {
  abi: _abi,

  storageSlots: _storageSlots,

  createInterface(): VerificationPredicateAbiInterface {
    return new Interface(_abi) as unknown as VerificationPredicateAbiInterface
  },

  connect(
    id: string | AbstractAddress,
    accountOrProvider: Account | Provider
  ): VerificationPredicateAbi {
    return new Contract(id, _abi, accountOrProvider) as unknown as VerificationPredicateAbi
  },

  async deployContract(
    bytecode: BytesLike,
    wallet: Account,
    options: DeployContractOptions = {}
  ): Promise<DeployContractResult<VerificationPredicateAbi>> {
    const factory = new ContractFactory(bytecode, _abi, wallet);

    return factory.deployContract<VerificationPredicateAbi>({
      storageSlots: _storageSlots,
      ...options,
    });
  },
}
