import { Providers } from '@/components/Providers';
import type { Metadata } from 'next';
import { headers } from 'next/headers';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const { get } = await headers();

  return (
    <html lang="en">
      <body>
        <Providers cookie={get('cookie')}>{children}</Providers>
      </body>
    </html>
  );
}
