/* Autogenerated file. Do not edit manually. */

import type { BytesLike, JsonAbi } from 'fuels';

export const generationDate = 1738383921738;
// biome-ignore lint: Autogenerated file
export const abi: JsonAbi = {
  programType: 'predicate',
  specVersion: '1',
  encodingVersion: '1',
  concreteTypes: [
    {
      type: 'b256',
      concreteTypeId:
        '7c5ee1cecf5f8eacd1284feb5f0bf2bdea533a51e2f0c9aabe9236d335989f3b',
    },
    {
      type: 'bool',
      concreteTypeId:
        'b760f44fa5965c2474a3b471467a22c43185152129295af588b022ae50b50903',
    },
    {
      type: 'u64',
      concreteTypeId:
        '1506e6f44c1d6291cdf46395a8e573276a4fa79e8ace3fc891e092ef32d1b0a0',
    },
  ],
  metadataTypes: [],
  functions: [
    {
      inputs: [
        {
          name: 'witness_index',
          concreteTypeId:
            '1506e6f44c1d6291cdf46395a8e573276a4fa79e8ace3fc891e092ef32d1b0a0',
        },
      ],
      name: 'main',
      output:
        'b760f44fa5965c2474a3b471467a22c43185152129295af588b022ae50b50903',
      attributes: null,
    },
  ],
  loggedTypes: [],
  messagesTypes: [],
  configurables: [
    {
      name: 'SIGNER',
      concreteTypeId:
        '7c5ee1cecf5f8eacd1284feb5f0bf2bdea533a51e2f0c9aabe9236d335989f3b',
      offset: 216,
    },
  ],
};
export const bin: BytesLike = new Uint8Array([
  26, 64, 48, 0, 80, 65, 0, 48, 26, 68, 80, 0, 186, 73, 0, 0, 50, 64, 4, 129,
  80, 65, 0, 32, 93, 73, 0, 0, 80, 65, 0, 8, 50, 64, 4, 130, 32, 69, 19, 0, 82,
  69, 16, 4, 74, 68, 0, 0, 185, 221, 182, 123, 37, 192, 186, 128, 107, 173, 35,
  97, 92, 196, 236, 99, 196, 251, 155, 10, 209, 76, 119, 215, 231, 148, 123,
  131, 24, 19, 215, 185, 0, 0, 0, 0, 0, 0, 0, 160, 48, 49, 50, 51, 52, 53, 54,
  55, 56, 57, 97, 98, 99, 100, 101, 102, 25, 69, 116, 104, 101, 114, 101, 117,
  109, 32, 83, 105, 103, 110, 101, 100, 32, 77, 101, 115, 115, 97, 103, 101, 58,
  10, 54, 52, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
  0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 204, 204, 204, 204, 204, 204, 0, 2,
  0, 0, 0, 0, 0, 0, 14, 88, 0, 0, 0, 0, 0, 0, 14, 112, 0, 0, 0, 0, 0, 0, 14,
  104, 0, 0, 0, 0, 0, 0, 9, 164, 0, 0, 0, 0, 0, 0, 7, 240, 0, 0, 0, 0, 0, 0, 0,
  0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
]);
