/* Autogenerated file. Do not edit manually. */

/* tslint:disable */
/* eslint-disable */

/*
  Fuels version: 0.93.0
  Forc version: 0.62.0
  Fuel-Core version: 0.31.0
*/

import type {
  BN,
  BigNumberish,
  BytesLike,
  Contract,
  DecodedValue,
  FunctionFragment,
  Interface,
  InvokeFunction,
} from 'fuels';

export type VerificationPredicateAbiConfigurables = Partial<{
  SIGNER: string;
}>;

export interface VerificationPredicateAbiInterface extends Interface {
  functions: {
    main: FunctionFragment;
  };
}

export class VerificationPredicateAbi extends Contract {
  interface: VerificationPredicateAbiInterface;
  functions: {
    main: InvokeFunction<[witness_index: BigNumberish], boolean>;
  };
}
