/* Autogenerated file. Do not edit manually. */

/* tslint:disable */
/* eslint-disable */

/*
  Fuels version: 0.83.0
  Forc version: 0.56.0
  Fuel-Core version: 0.24.3
*/

export type { CounterContractAbi } from './CounterContractAbi';

export { CounterContractAbi__factory } from './factories/CounterContractAbi__factory';
