/* Autogenerated file. Do not edit manually. */

import { VerificationPredicate as Predicate1725378313230 } from './0xb2e7afecbc573e7412ca0bbb8d8f01d75c5c63f09e14c0921913ca9b7df70e63';

export default {
  '0x279df00c04dcb33686e6212b4da2a08dbd5a2fa5cb5b2d0998aeb98906f1d7d7': {
    predicate: Predicate1725378313230,
    generatedAt: 1725378313230,
  },
};
