/* Autogenerated file. Do not edit manually. */

import type { PredicateVersion } from '../../types';
import {
  abi as abi1725378729292,
  bin as bin1725378729292,
  generationDate as generationDate1725378729292,
} from './0xb2e7afecbc573e7412ca0bbb8d8f01d75c5c63f09e14c0921913ca9b7df70e63';

export default {
  '0xb2e7afecbc573e7412ca0bbb8d8f01d75c5c63f09e14c0921913ca9b7df70e63': {
    predicate: { abi: abi1725378729292, bin: bin1725378729292 },
    generatedAt: generationDate1725378729292,
  },
} as Record<string, PredicateVersion>;
