// Social login icon (generic user/social icon)
export const SOCIAL_ICON =
  'data:image/svg+xml;base64,PHN2ZyB3aWR0aD0iNTEyIiBoZWlnaHQ9IjUxMiIgdmlld0JveD0iMCAwIDUxMiA1MTIiIGZpbGw9Im5vbmUiIHhtbG5zPSJodHRwOi8vd3d3LnczLm9yZy8yMDAwL3N2ZyI+CjxjaXJjbGUgY3g9IjI1NiIgY3k9IjI1NiIgcj0iMjU2IiBmaWxsPSIjRjVGNUY1Ii8+CjxjaXJjbGUgY3g9IjI1NiIgY3k9IjIwMCIgcj0iODAiIGZpbGw9IiM2NjY2NjYiLz4KPHBhdGggZD0iTTEyOCA0MzJDMTI4IDM2MS4zMDggMTg1LjMwOCAzMDQgMjU2IDMwNEMzMjYuNjkyIDMwNCAzODQgMzYxLjMwOCAzODQgNDMyIiBzdHJva2U9IiM2NjY2NjYiIHN0cm9rZS13aWR0aD0iNjQiIHN0cm9rZS1saW5lY2FwPSJyb3VuZCIvPgo8L3N2Zz4K';

export const HAS_WINDOW = typeof window !== 'undefined';
export const WINDOW = HAS_WINDOW ? window : null;
