/* Autogenerated file. Do not edit manually. */

import { Predicate as Predicate1722561429916 } from './0x279df00c04dcb33686e6212b4da2a08dbd5a2fa5cb5b2d0998aeb98906f1d7d7';

export const PREDICATE_VERSIONS = {
  '0x279df00c04dcb33686e6212b4da2a08dbd5a2fa5cb5b2d0998aeb98906f1d7d7': {
    predicate: Predicate1722561429916,
    generatedAt: 1722561429916,
  },
};
