/* Autogenerated file. Do not edit manually. */

import {
  abi as abi1725479113004,
  bin as bin1725479113004,
  generationDate as generationDate1725479113004,
} from './0xfdac03fc617c264fa6f325fd6f4d2a5470bf44cfbd33bc11efb3bf8b7ee2e938';

export const PREDICATE_VERSIONS = {
  '0xfdac03fc617c264fa6f325fd6f4d2a5470bf44cfbd33bc11efb3bf8b7ee2e938': {
    predicate: { abi: abi1725479113004, bin: bin1725479113004 },
    generatedAt: generationDate1725479113004,
  },
};
