/* Autogenerated file. Do not edit manually. */

/* tslint:disable */
/* eslint-disable */

/*
  Fuels version: 0.92.0
  Forc version: 0.61.2
  Fuel-Core version: 0.31.0
*/

export type { VerificationPredicateAbi } from './VerificationPredicateAbi';

export { VerificationPredicateAbi__factory } from './factories/VerificationPredicateAbi__factory';
